import { Router } from 'express';
import { createCustomer, deleteCustomer, getCustomerById, getCustomers, updateCustomer } from '../controllers/customer.controller';
import { verifyToken } from '../middlewares/auth.middleware';
import { validate } from '../middlewares/validate.middleware';
import { createCustomerSchema, customerIdSchema, updateCustomerSchema } from '../schemas/customer.schema';
const router = Router();
router.use(verifyToken);
router.get('/', getCustomers);
router.get('/:id', validate(customerIdSchema), getCustomerById);
router.post('/', validate(createCustomerSchema), createCustomer);
router.put('/:id', validate(updateCustomerSchema), updateCustomer);
router.patch('/:id', validate(updateCustomerSchema), updateCustomer);
router.delete('/:id', validate(customerIdSchema), deleteCustomer);
export default router;
