import { Router } from 'express';
import { createTask, deleteTask, getTasks, updateTask, updateTaskStatus } from '../controllers/task.controller';
import { verifyToken } from '../middlewares/auth.middleware';
import { validate } from '../middlewares/validate.middleware';
import { createTaskSchema, taskIdSchema, updateTaskSchema, updateTaskStatusSchema } from '../schemas/task.schema';
const router = Router();
router.use(verifyToken);
router.get('/', getTasks);
router.post('/', validate(createTaskSchema), createTask);
router.put('/:id', validate(updateTaskStatusSchema), updateTaskStatus);
router.patch('/:id/status', validate(updateTaskStatusSchema), updateTaskStatus);
router.put('/:id/edit', validate(updateTaskSchema), updateTask);
router.patch('/:id', validate(updateTaskSchema), updateTask);
router.delete('/:id', validate(taskIdSchema), deleteTask);
export default router;
