DO $$ BEGIN
  CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'DISABLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ACCESS_DENIED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ROLE_CHANGED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ACCOUNT_STATUS_CHANGED';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "User_role_status_idx" ON "User"("role", "status");
